version: "3.8"

services:
    server-nodejs:
        build: 
            context: ./server
        container_name: ndtnf-server
        restart: always
        user: node
        working_dir: /app/server
        env_file:
            - .env
        volumes:
            - ./:/app:cached
        ports:
            - 3000:3000

    mongodb:
        image: mongo
        container_name: ndtnf-mongodb
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
        volumes:
            - ./database/mongodb:/data/db
        ports:
            - ${MONGODB_PORT}:${MONGODB_PORT}